num_epochs: 2  # Increased from 1 to 2, usually 2-3 epochs are sufficient
warmup_ratio: 0.1
num_workers: 16  # 128-core system, set to 16 workers 
device: "cuda"

output:
  dir: ${paths.output_dir}/e5-finetuned-v1

logging:
  log_every_steps: 100
